num1 = int(input('Enter 1st number: \n'))
num2 = int(input('Enter 2nd number: \n'))
num3 = int(input('Enter 3rd number: \n'))
num4 = int(input('Enter 4th number: \n'))
num5 = int(input('Enter 5th number: \n'))
num6 = int(input('Enter 6th number: \n'))
num7 = int(input('Enter 7th number: \n'))
num8 = int(input('Enter 8th number: \n'))
s = {num1, num2, num3, num4, num5, num6, num7, num8}
print(s)